#========================================server config=====================================
server:
  port: 9100
#========================================spring config=====================================
spring:
  application:
    name: seata-springcloud-account
  devtools:
    restart:
      enabled: false
#========================================MySQL config=====================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fescardubbo3?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root

  cloud:
    alibaba:
      seata:
        txServiceGroup: my_test_tx_group
logging:
  level:
    io:
      seata: info
#========================================eureka config=====================================
eureka:
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka/
